### PR TITLE
WatermelonProblem.cpp

### PR DESCRIPTION
**Pull request by aparna03dubey**
Solution of the Watermelon Problem on Codeforces Div 2A

### CODE REVIEW

**Comment by SanyaGera** [comment]
Please change the file name to Watermelon-problem.cpp. Everything else looks great!

**Comment by aparna03dubey** [comment]
Done

**Comment by aparna03dubey** [comment]
Heyy!!
Is it fine now??

**Comment by SanyaGera** [comment]
Yes

**Pull request merged**
